### ISSUE TITLE
A quick question about zooming in on ticks

### ISSUE THREAD

**Issue by ariesfan405** [tsengshao/CDGC-2024#6]
@mileshsieh @tsengshao 
zoom in時的時間ticks有小數點，是否可以改成只有整數小時顯示，或是分鐘？
![temp](https://github.com/user-attachments/assets/617c4637-0291-4680-a6c8-e5e28935c958)

**Comment by mileshsieh** [comment]
能不能在建立dataPlotters 的class時候
傳入的data_dim['t']直接給某個時間變數
然後另外tick_dim['t']傳入' 3-hour' '5-minute'之類的設定
由此控制要有tick在小時還是分鐘還有他的間距？

我在想這個設定可以mapping到matplotlib 時間軸的用法上：
[interval,time_unit]=tick_dim['t'].split('-')
time_mapper={'hour':[matplotlib.dates.HourLocator(interval=int(intvl)),'%H'],
                          'minute':[matplotlib.dates.MinuteLocator(interval=int(intvl)),'%M'],
繪圖時再用
ax.xaxis.set_major_locator(time_mapper[time_unit][0])
ax.xaxis.set_major_formatter(matplotlib.dates.DateFormatter(time_mapper[time_unit][1]))
這樣要zoom in到幾個小時內就可以自己設定看看大家覺得如何

**Comment by tsengshao** [comment]
@mileshsieh sounds good.

@ariesfan405  has a simplified version but still has a few constraints (force limits to 0.5 hours). He will become our co-author and push his version.

We can discuss general methods to solve this problem in the future. (might use mileshsieh method ?)

**Comment by mileshsieh** [comment]
Problem solved by Shao.
Now we have a nice auto-ticks in the time-axis.
