### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'colormaps'

### ISSUE THREAD

**Issue by tsengshao** [tsengshao/CDGC-2024#7]
in plottools, please change the older method to get the colormap in matplotlib. `cmap=plt.get_cmap(name)`
it can be available for older versions of matplotlib.

**Comment by ariesfan405** [comment]
the version issue with get colormaps has been fixed in the latest version by using the function matplotlib.pyplot.get_cmap().
Thanks!
